services:
  frontend:
    image: banking-demo/banking-demo-webapp:latest
    container_name: banking-demo-frontend
    ports:
      - "7070:7070"
    depends_on:
      - backend

  backend:
    image: banking-demo/banking-demo-backend:latest
    container_name: banking-demo-backend
    ports:
      - "8080:8080"
